std_msgs/Header header

geometry_msgs/Pose nose
geometry_msgs/Pose neck
geometry_msgs/Pose r_should
geometry_msgs/Pose r_elbow
geometry_msgs/Pose r_hand
geometry_msgs/Pose l_should
geometry_msgs/Pose l_elbow
geometry_msgs/Pose l_hand
geometry_msgs/Pose c_waist
geometry_msgs/Pose r_waist
geometry_msgs/Pose r_nee
geometry_msgs/Pose r_foot
geometry_msgs/Pose l_waist
geometry_msgs/Pose l_nee
geometry_msgs/Pose l_foot
geometry_msgs/Pose r_eye
geometry_msgs/Pose l_eye
geometry_msgs/Pose r_ear
geometry_msgs/Pose l_ear


